data <- fread("household_power_consumption.txt", sep = ";", na.strings = "?")
subset <- subset(data, Date == '2/2/2007' | Date == '1/2/2007')
png("plot1.png", width = 480, height = 480, units = "px")
hist(subset$Global_active_power, main="Global Active Power", col="red", xlab = "Global Active Power(kilowatts)")
dev.off()